# -*- coding: utf-8 -*-
"""260318_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLH4p9vLieVn48ofbGX04256PsWbgqUS
"""

#pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime

# --- CẤU HÌNH TRANG ---
st.set_page_config(
    page_title="NLP Quora Question Pairs",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- GIAO DIỆN BÊN HÔNG (SIDEBAR) ---
with st.sidebar:
    st.title("🎛️ Bảng điều khiển")
    st.markdown("---")

    # Menu chính
    menu_option = st.selectbox(
        "Chọn chức năng:",
        ["📊 Trang chủ", "📈 Phân tích dữ liệu", "🔍 Tìm kiếm câu hỏi tương tự", "📋 Thống kê"]
    )

    st.markdown("---")
    st.subheader("⚙️ Cài đặt")

    # Tùy chọn tải file dữ liệu
    uploaded_file = st.file_uploader("Tải file CSV:", type=["csv"])

    # Cài đặt mô hình
    model_type = st.selectbox(
        "Chọn mô hình:",
        ["BERT", "Word2Vec", "TF-IDF", "GloVe"]
    )

    # Ngưỡng similarity
    similarity_threshold = st.slider(
        "Ngưỡng độ tương tự:",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.05
    )

# --- HÀM XỬ LÝ DỮ LIỆU ---
@st.cache_data
def tải_dữ_liệu(file=None):
    """Tải dữ liệu từ file hoặc dữ liệu mặc định"""
    if file is not None:
        return pd.read_csv(file)
    else:
        # Dữ liệu mẫu
        data = {
            'id': range(1, 6),
            'question1': [
                'What is Python?',
                'How to learn machine learning?',
                'What is NLP?',
                'Explain deep learning',
                'What is a neural network?'
            ],
            'question2': [
                'Python là gì?',
                'Làm sao học máy học?',
                'NLP là gì?',
                'Học sâu là gì?',
                'Mạng thần kinh nhân tạo là gì?'
            ],
            'is_duplicate': [1, 1, 1, 0, 1]
        }
        return pd.DataFrame(data)

@st.cache_data
def tính_toán_thống_kê(df):
    """Tính toán thống kê cơ bản"""
    total_pairs = len(df)
    duplicates = df['is_duplicate'].sum() if 'is_duplicate' in df.columns else 0
    duplicate_ratio = (duplicates / total_pairs * 100) if total_pairs > 0 else 0

    return {
        'total_pairs': total_pairs,
        'duplicates': duplicates,
        'duplicate_ratio': duplicate_ratio
    }

def độ_tương_tự_giữa_câu(q1, q2):
    """Tính độ tương tự đơn giản giữa hai câu"""
    # Placeholder cho hàm tính similarity thực tế
    similarity = np.random.rand()
    return similarity

# --- PHẦN 3: HIỂN THỊ GIAO DIỆN CHÍNH ---
st.set_page_config(page_title="NLP Quora Question Pairs")

if menu_option == "📊 Trang chủ":
    st.header("🚀 Ứng dụng phân tích câu hỏi tương tự trên Quora")
    st.markdown("""
    Chào mừng bạn đến với ứng dụng phân tích câu hỏi tương tự!

    **Các chức năng chính:**
    - 📊 Phân tích và khám phá dữ liệu
    - 🔍 Tìm kiếm các câu hỏi tương tự
    - 📈 Xem thống kê chi tiết
    - ⚙️ So sánh mô hình khác nhau
    """)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.info("💡 **Mẹo:** Tải file CSV của bạn từ sidebar để bắt đầu phân tích")

elif menu_option == "📈 Phân tích dữ liệu":
    st.header("📈 Phân tích dữ liệu")

    df = tải_dữ_liệu(uploaded_file)

    st.subheader("📋 Dữ liệu gốc")
    st.dataframe(df, use_container_width=True)

    # Hiển thị thống kê
    st.subheader("📊 Thống kê cơ bản")
    stats = tính_toán_thống_kê(df)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Tổng cặp câu hỏi", stats['total_pairs'])
    with col2:
        st.metric("Cặp trùng lặp", stats['duplicates'])
    with col3:
        st.metric("Tỷ lệ trùng lặp", f"{stats['duplicate_ratio']:.2f}%")

    # Hiển thị chi tiết dữ liệu
    if st.checkbox("Hiển thị thông tin chi tiết"):
        st.write(df.describe())

elif menu_option == "🔍 Tìm kiếm câu hỏi tương tự":
    st.header("🔍 Tìm kiếm câu hỏi tương tự")

    df = tải_dữ_liệu(uploaded_file)

    st.markdown(f"**Mô hình hiện tại:** {model_type} | **Ngưỡng:** {similarity_threshold}")

    col1, col2 = st.columns(2)

    with col1:
        query = st.text_area("Nhập câu hỏi cần tìm:", placeholder="Ví dụ: What is machine learning?")

    if st.button("🔎 Tìm kiếm", use_container_width=True):
        if query:
            st.subheader("Kết quả tương tự:")

            results = []
            for idx, row in df.iterrows():
                q = row.get('question1', '') or row.get('question2', '')
                similarity = độ_tương_tự_giữa_câu(query, q)

                if similarity >= similarity_threshold:
                    results.append({
                        'ID': idx + 1,
                        'Câu hỏi': q,
                        'Độ tương tự': f"{similarity:.2%}",
                        'Mô hình': model_type
                    })

            if results:
                st.dataframe(pd.DataFrame(results), use_container_width=True)
            else:
                st.warning("❌ Không tìm thấy câu hỏi tương tự với ngưỡng được chọn")
        else:
            st.error("⚠️ Vui lòng nhập câu hỏi để tìm kiếm")

elif menu_option == "📋 Thống kê":
    st.header("📋 Thống kê chi tiết")

    df = tải_dữ_liệu(uploaded_file)
    stats = tính_toán_thống_kê(df)

    # Các cột thống kê
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("📊 Thông tin chung")
        st.json({
            "Tổng cặp câu hỏi": stats['total_pairs'],
            "Cặp trùng lặp": stats['duplicates'],
            "Cặp không trùng": stats['total_pairs'] - stats['duplicates'],
            "Tỷ lệ trùng (%)": round(stats['duplicate_ratio'], 2)
        })

    with col2:
        st.subheader("🔧 Cài đặt mô hình")
        st.json({
            "Mô hình hiện tại": model_type,
            "Ngưỡng similarity": similarity_threshold,
            "Phiên bản": "1.0",
            "Ngày cập nhật": datetime.now().strftime("%Y-%m-%d")
        })

    # Biểu đồ phân bố
    if 'is_duplicate' in df.columns:
        st.subheader("📈 Biểu đồ phân bố")
        duplicate_counts = df['is_duplicate'].value_counts()
        st.bar_chart(duplicate_counts)

# --- FOOTER ---
st.markdown("---")
st.markdown(
    "<p style='text-align: center; color: gray;'>NLP Quora Question Pairs Analysis © 2026</p>",
    unsafe_allow_html=True
)